### ISSUE TITLE
Collected metric was collected before with the same name and label values

### ISSUE THREAD

**Issue by dgarcdu** [SUSE/sap_host_exporter#57]
Hello.
I have recently deployed this exporter on several instances, and in some cases I cannot get any metrics.
The exporters start and run without any apparent problems, but when trying to see what are they exposing via curl, I get the following:
```
curl localhost:9680/metrics
An error has occurred while serving metrics:

collected metric "sap_start_service_instances" { label:<name:"SID" value:"TGR" > label:<name:"features" value:"MESSAGESERVER|ENQUE" > label:<name:"instance_hostname" value:"saptgrcs" > label:<name:"instance_name" value:"ASCS01" > label:<name:"instance_number" value:"1" > label:<name:"start_priority" value:"1" > gauge:<value:2 > } was collected before with the same name and label values
```
The config file:
```yaml
# The listening TCP/IP address and port.
address: "0.0.0.0"
port: "9680"

# The log level.
#
# Possible values, from less to most verbose: error, warn, info, debug.
log-level: "info"

# The path to a Unix Domain Socket to access SAPControl locally.
#
# This is usually /tmp/.sapstream5<instance number>13
#
# If this is specified, sap-control-url setting will be ignored.
# UDS connection doesn't require authentication
sap-control-uds: "/tmp/.sapstream50113"
```
In another instance:
```
curl http://localhost:9680/metrics
An error has occurred while serving metrics:

collected metric "sap_start_service_instances" { label:<name:"SID" value:"TGR" > label:<name:"features" value:"ENQREP" > label:<name:"instance_hostname" value:"saptgrers" > label:<name:"instance_name" value:"ERS02" > label:<name:"instance_number" value:"2" > label:<name:"start_priority" value:"0.5" > gauge:<value:1 > } was collected before with the same name and label values
```
And the corresponding config:
```yaml
# The listening TCP/IP address and port.
address: "0.0.0.0"
port: "9680"

# The log level.
#
# Possible values, from less to most verbose: error, warn, info, debug.
log-level: "info"

# The path to a Unix Domain Socket to access SAPControl locally.
#
# This is usually /tmp/.sapstream5<instance number>13
#
# If this is specified, sap-control-url setting will be ignored.
# UDS connection doesn't require authentication
sap-control-uds: "/tmp/.sapstream50213"
```

In any other instances, the exporters are running fine and serving metrics without any problem. It is just in these two I'm getting the error messages.

AFAIK that error message usually appears when there are duplicated metrics at the source, but I do not know much about SAP systems and maybe I'm missing something here, so any help would be very appreciated.

Thanks in advance.
